// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/participant/v1/course.proto

package participantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCourseRequest) Reset() {
	*x = AddCourseRequest{}
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCourseRequest) ProtoMessage() {}

func (x *AddCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCourseRequest.ProtoReflect.Descriptor instead.
func (*AddCourseRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_course_proto_rawDescGZIP(), []int{0}
}

func (x *AddCourseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddCourseRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type AddCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCourseResponse) Reset() {
	*x = AddCourseResponse{}
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCourseResponse) ProtoMessage() {}

func (x *AddCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCourseResponse.ProtoReflect.Descriptor instead.
func (*AddCourseResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_course_proto_rawDescGZIP(), []int{1}
}

func (x *AddCourseResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_course_proto_rawDescGZIP(), []int{2}
}

func (x *Course) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Course) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Course) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Course) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Course) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesRequest) Reset() {
	*x = GetCoursesRequest{}
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesRequest) ProtoMessage() {}

func (x *GetCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesRequest.ProtoReflect.Descriptor instead.
func (*GetCoursesRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_course_proto_rawDescGZIP(), []int{3}
}

type GetCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCoursesResponse) Reset() {
	*x = GetCoursesResponse{}
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoursesResponse) ProtoMessage() {}

func (x *GetCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoursesResponse.ProtoReflect.Descriptor instead.
func (*GetCoursesResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

var File_proto_services_participant_v1_course_proto protoreflect.FileDescriptor

const file_proto_services_participant_v1_course_proto_rawDesc = "" +
	"\n" +
	"*proto/services/participant/v1/course.proto\x12\x17services.participant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\":\n" +
	"\x10AddCourseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"#\n" +
	"\x11AddCourseResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xb6\x01\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x13\n" +
	"\x11GetCoursesRequest\"O\n" +
	"\x12GetCoursesResponse\x129\n" +
	"\acourses\x18\x01 \x03(\v2\x1f.services.participant.v1.CourseR\acourses2\xda\x01\n" +
	"\rCourseService\x12b\n" +
	"\tAddCourse\x12).services.participant.v1.AddCourseRequest\x1a*.services.participant.v1.AddCourseResponse\x12e\n" +
	"\n" +
	"GetCourses\x12*.services.participant.v1.GetCoursesRequest\x1a+.services.participant.v1.GetCoursesResponseBKZIgithub.com/loanem-backend/protos/pb/services/participant/v1;participantv1b\x06proto3"

var (
	file_proto_services_participant_v1_course_proto_rawDescOnce sync.Once
	file_proto_services_participant_v1_course_proto_rawDescData []byte
)

func file_proto_services_participant_v1_course_proto_rawDescGZIP() []byte {
	file_proto_services_participant_v1_course_proto_rawDescOnce.Do(func() {
		file_proto_services_participant_v1_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_course_proto_rawDesc), len(file_proto_services_participant_v1_course_proto_rawDesc)))
	})
	return file_proto_services_participant_v1_course_proto_rawDescData
}

var file_proto_services_participant_v1_course_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_services_participant_v1_course_proto_goTypes = []any{
	(*AddCourseRequest)(nil),      // 0: services.participant.v1.AddCourseRequest
	(*AddCourseResponse)(nil),     // 1: services.participant.v1.AddCourseResponse
	(*Course)(nil),                // 2: services.participant.v1.Course
	(*GetCoursesRequest)(nil),     // 3: services.participant.v1.GetCoursesRequest
	(*GetCoursesResponse)(nil),    // 4: services.participant.v1.GetCoursesResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_services_participant_v1_course_proto_depIdxs = []int32{
	5, // 0: services.participant.v1.Course.created_at:type_name -> google.protobuf.Timestamp
	5, // 1: services.participant.v1.Course.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: services.participant.v1.GetCoursesResponse.courses:type_name -> services.participant.v1.Course
	0, // 3: services.participant.v1.CourseService.AddCourse:input_type -> services.participant.v1.AddCourseRequest
	3, // 4: services.participant.v1.CourseService.GetCourses:input_type -> services.participant.v1.GetCoursesRequest
	1, // 5: services.participant.v1.CourseService.AddCourse:output_type -> services.participant.v1.AddCourseResponse
	4, // 6: services.participant.v1.CourseService.GetCourses:output_type -> services.participant.v1.GetCoursesResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_services_participant_v1_course_proto_init() }
func file_proto_services_participant_v1_course_proto_init() {
	if File_proto_services_participant_v1_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_course_proto_rawDesc), len(file_proto_services_participant_v1_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_participant_v1_course_proto_goTypes,
		DependencyIndexes: file_proto_services_participant_v1_course_proto_depIdxs,
		MessageInfos:      file_proto_services_participant_v1_course_proto_msgTypes,
	}.Build()
	File_proto_services_participant_v1_course_proto = out.File
	file_proto_services_participant_v1_course_proto_goTypes = nil
	file_proto_services_participant_v1_course_proto_depIdxs = nil
}
