// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/participant/v1/participant.proto

package participantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nim           string                 `protobuf:"bytes,3,opt,name=nim,proto3" json:"nim,omitempty"`
	TeamId        int32                  `protobuf:"varint,4,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantRequest) Reset() {
	*x = AddParticipantRequest{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantRequest) ProtoMessage() {}

func (x *AddParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantRequest.ProtoReflect.Descriptor instead.
func (*AddParticipantRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{0}
}

func (x *AddParticipantRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddParticipantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddParticipantRequest) GetNim() string {
	if x != nil {
		return x.Nim
	}
	return ""
}

func (x *AddParticipantRequest) GetTeamId() int32 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type AddParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddParticipantResponse) Reset() {
	*x = AddParticipantResponse{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddParticipantResponse) ProtoMessage() {}

func (x *AddParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddParticipantResponse.ProtoReflect.Descriptor instead.
func (*AddParticipantResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{1}
}

var File_proto_services_participant_v1_participant_proto protoreflect.FileDescriptor

const file_proto_services_participant_v1_participant_proto_rawDesc = "" +
	"\n" +
	"/proto/services/participant/v1/participant.proto\x12\x17services.participant.v1\"f\n" +
	"\x15AddParticipantRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03nim\x18\x03 \x01(\tR\x03nim\x12\x17\n" +
	"\ateam_id\x18\x04 \x01(\x05R\x06teamId\"\x18\n" +
	"\x16AddParticipantResponse2\x87\x01\n" +
	"\x12ParticipantService\x12q\n" +
	"\x0eAddParticipant\x12..services.participant.v1.AddParticipantRequest\x1a/.services.participant.v1.AddParticipantResponseBKZIgithub.com/loanem-backend/protos/pb/services/participant/v1;participantv1b\x06proto3"

var (
	file_proto_services_participant_v1_participant_proto_rawDescOnce sync.Once
	file_proto_services_participant_v1_participant_proto_rawDescData []byte
)

func file_proto_services_participant_v1_participant_proto_rawDescGZIP() []byte {
	file_proto_services_participant_v1_participant_proto_rawDescOnce.Do(func() {
		file_proto_services_participant_v1_participant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_participant_proto_rawDesc), len(file_proto_services_participant_v1_participant_proto_rawDesc)))
	})
	return file_proto_services_participant_v1_participant_proto_rawDescData
}

var file_proto_services_participant_v1_participant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_services_participant_v1_participant_proto_goTypes = []any{
	(*AddParticipantRequest)(nil),  // 0: services.participant.v1.AddParticipantRequest
	(*AddParticipantResponse)(nil), // 1: services.participant.v1.AddParticipantResponse
}
var file_proto_services_participant_v1_participant_proto_depIdxs = []int32{
	0, // 0: services.participant.v1.ParticipantService.AddParticipant:input_type -> services.participant.v1.AddParticipantRequest
	1, // 1: services.participant.v1.ParticipantService.AddParticipant:output_type -> services.participant.v1.AddParticipantResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_services_participant_v1_participant_proto_init() }
func file_proto_services_participant_v1_participant_proto_init() {
	if File_proto_services_participant_v1_participant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_participant_proto_rawDesc), len(file_proto_services_participant_v1_participant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_participant_v1_participant_proto_goTypes,
		DependencyIndexes: file_proto_services_participant_v1_participant_proto_depIdxs,
		MessageInfos:      file_proto_services_participant_v1_participant_proto_msgTypes,
	}.Build()
	File_proto_services_participant_v1_participant_proto = out.File
	file_proto_services_participant_v1_participant_proto_goTypes = nil
	file_proto_services_participant_v1_participant_proto_depIdxs = nil
}
