// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/participant/v1/participant.proto

package participantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int32                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Name          uint32                 `protobuf:"varint,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClassRequest) Reset() {
	*x = AddClassRequest{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClassRequest) ProtoMessage() {}

func (x *AddClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClassRequest.ProtoReflect.Descriptor instead.
func (*AddClassRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{0}
}

func (x *AddClassRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AddClassRequest) GetName() uint32 {
	if x != nil {
		return x.Name
	}
	return 0
}

type AddClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClassResponse) Reset() {
	*x = AddClassResponse{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClassResponse) ProtoMessage() {}

func (x *AddClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClassResponse.ProtoReflect.Descriptor instead.
func (*AddClassResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{1}
}

func (x *AddClassResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Class struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CourseId      int32                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Name          uint32                 `protobuf:"varint,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{2}
}

func (x *Class) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Class) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *Class) GetName() uint32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *Class) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Class) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetClassesByCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int32                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassesByCourseIDRequest) Reset() {
	*x = GetClassesByCourseIDRequest{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassesByCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassesByCourseIDRequest) ProtoMessage() {}

func (x *GetClassesByCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassesByCourseIDRequest.ProtoReflect.Descriptor instead.
func (*GetClassesByCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{3}
}

func (x *GetClassesByCourseIDRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type GetClassesByCourseIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*Class               `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassesByCourseIDResponse) Reset() {
	*x = GetClassesByCourseIDResponse{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassesByCourseIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassesByCourseIDResponse) ProtoMessage() {}

func (x *GetClassesByCourseIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassesByCourseIDResponse.ProtoReflect.Descriptor instead.
func (*GetClassesByCourseIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{4}
}

func (x *GetClassesByCourseIDResponse) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

type AddTeamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       int32                  `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Number        int32                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamRequest) Reset() {
	*x = AddTeamRequest{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamRequest) ProtoMessage() {}

func (x *AddTeamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamRequest.ProtoReflect.Descriptor instead.
func (*AddTeamRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{5}
}

func (x *AddTeamRequest) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *AddTeamRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *AddTeamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddTeamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamResponse) Reset() {
	*x = AddTeamResponse{}
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamResponse) ProtoMessage() {}

func (x *AddTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_participant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamResponse.ProtoReflect.Descriptor instead.
func (*AddTeamResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_participant_proto_rawDescGZIP(), []int{6}
}

func (x *AddTeamResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_services_participant_v1_participant_proto protoreflect.FileDescriptor

const file_proto_services_participant_v1_participant_proto_rawDesc = "" +
	"\n" +
	"/proto/services/participant/v1/participant.proto\x12\x17services.participant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x0fAddClassRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x05R\bcourseId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\rR\x04name\"\"\n" +
	"\x10AddClassResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xbe\x01\n" +
	"\x05Class\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x05R\bcourseId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\rR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x1bGetClassesByCourseIDRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x05R\bcourseId\"X\n" +
	"\x1cGetClassesByCourseIDResponse\x128\n" +
	"\aclasses\x18\x01 \x03(\v2\x1e.services.participant.v1.ClassR\aclasses\"W\n" +
	"\x0eAddTeamRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\x05R\aclassId\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x05R\x06number\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"!\n" +
	"\x0fAddTeamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id2\xd9\x02\n" +
	"\x12ParticipantService\x12_\n" +
	"\bAddClass\x12(.services.participant.v1.AddClassRequest\x1a).services.participant.v1.AddClassResponse\x12\x83\x01\n" +
	"\x14GetClassesByCourseID\x124.services.participant.v1.GetClassesByCourseIDRequest\x1a5.services.participant.v1.GetClassesByCourseIDResponse\x12\\\n" +
	"\aAddTeam\x12'.services.participant.v1.AddTeamRequest\x1a(.services.participant.v1.AddTeamResponseBKZIgithub.com/loanem-backend/protos/pb/services/participant/v1;participantv1b\x06proto3"

var (
	file_proto_services_participant_v1_participant_proto_rawDescOnce sync.Once
	file_proto_services_participant_v1_participant_proto_rawDescData []byte
)

func file_proto_services_participant_v1_participant_proto_rawDescGZIP() []byte {
	file_proto_services_participant_v1_participant_proto_rawDescOnce.Do(func() {
		file_proto_services_participant_v1_participant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_participant_proto_rawDesc), len(file_proto_services_participant_v1_participant_proto_rawDesc)))
	})
	return file_proto_services_participant_v1_participant_proto_rawDescData
}

var file_proto_services_participant_v1_participant_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_services_participant_v1_participant_proto_goTypes = []any{
	(*AddClassRequest)(nil),              // 0: services.participant.v1.AddClassRequest
	(*AddClassResponse)(nil),             // 1: services.participant.v1.AddClassResponse
	(*Class)(nil),                        // 2: services.participant.v1.Class
	(*GetClassesByCourseIDRequest)(nil),  // 3: services.participant.v1.GetClassesByCourseIDRequest
	(*GetClassesByCourseIDResponse)(nil), // 4: services.participant.v1.GetClassesByCourseIDResponse
	(*AddTeamRequest)(nil),               // 5: services.participant.v1.AddTeamRequest
	(*AddTeamResponse)(nil),              // 6: services.participant.v1.AddTeamResponse
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_proto_services_participant_v1_participant_proto_depIdxs = []int32{
	7, // 0: services.participant.v1.Class.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: services.participant.v1.Class.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: services.participant.v1.GetClassesByCourseIDResponse.classes:type_name -> services.participant.v1.Class
	0, // 3: services.participant.v1.ParticipantService.AddClass:input_type -> services.participant.v1.AddClassRequest
	3, // 4: services.participant.v1.ParticipantService.GetClassesByCourseID:input_type -> services.participant.v1.GetClassesByCourseIDRequest
	5, // 5: services.participant.v1.ParticipantService.AddTeam:input_type -> services.participant.v1.AddTeamRequest
	1, // 6: services.participant.v1.ParticipantService.AddClass:output_type -> services.participant.v1.AddClassResponse
	4, // 7: services.participant.v1.ParticipantService.GetClassesByCourseID:output_type -> services.participant.v1.GetClassesByCourseIDResponse
	6, // 8: services.participant.v1.ParticipantService.AddTeam:output_type -> services.participant.v1.AddTeamResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_services_participant_v1_participant_proto_init() }
func file_proto_services_participant_v1_participant_proto_init() {
	if File_proto_services_participant_v1_participant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_participant_proto_rawDesc), len(file_proto_services_participant_v1_participant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_participant_v1_participant_proto_goTypes,
		DependencyIndexes: file_proto_services_participant_v1_participant_proto_depIdxs,
		MessageInfos:      file_proto_services_participant_v1_participant_proto_msgTypes,
	}.Build()
	File_proto_services_participant_v1_participant_proto = out.File
	file_proto_services_participant_v1_participant_proto_goTypes = nil
	file_proto_services_participant_v1_participant_proto_depIdxs = nil
}
