// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/participant/v1/team.proto

package participantv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddClassesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int32                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Names         []string               `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClassesRequest) Reset() {
	*x = AddClassesRequest{}
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClassesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClassesRequest) ProtoMessage() {}

func (x *AddClassesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClassesRequest.ProtoReflect.Descriptor instead.
func (*AddClassesRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_team_proto_rawDescGZIP(), []int{0}
}

func (x *AddClassesRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *AddClassesRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type AddClassesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddClassesResponse) Reset() {
	*x = AddClassesResponse{}
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddClassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddClassesResponse) ProtoMessage() {}

func (x *AddClassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddClassesResponse.ProtoReflect.Descriptor instead.
func (*AddClassesResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_team_proto_rawDescGZIP(), []int{1}
}

type Class struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CourseId      int32                  `protobuf:"varint,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseName    string                 `protobuf:"bytes,4,opt,name=course_name,json=courseName,proto3" json:"course_name,omitempty"`
	CourseYear    int32                  `protobuf:"varint,5,opt,name=course_year,json=courseYear,proto3" json:"course_year,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Class) Reset() {
	*x = Class{}
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_team_proto_rawDescGZIP(), []int{2}
}

func (x *Class) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

func (x *Class) GetCourseName() string {
	if x != nil {
		return x.CourseName
	}
	return ""
}

func (x *Class) GetCourseYear() int32 {
	if x != nil {
		return x.CourseYear
	}
	return 0
}

func (x *Class) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Class) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetClassesByCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      int32                  `protobuf:"varint,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassesByCourseIDRequest) Reset() {
	*x = GetClassesByCourseIDRequest{}
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassesByCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassesByCourseIDRequest) ProtoMessage() {}

func (x *GetClassesByCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassesByCourseIDRequest.ProtoReflect.Descriptor instead.
func (*GetClassesByCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_team_proto_rawDescGZIP(), []int{3}
}

func (x *GetClassesByCourseIDRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type GetClassesByCourseIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Classes       []*Class               `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassesByCourseIDResponse) Reset() {
	*x = GetClassesByCourseIDResponse{}
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassesByCourseIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassesByCourseIDResponse) ProtoMessage() {}

func (x *GetClassesByCourseIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassesByCourseIDResponse.ProtoReflect.Descriptor instead.
func (*GetClassesByCourseIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_team_proto_rawDescGZIP(), []int{4}
}

func (x *GetClassesByCourseIDResponse) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

type AddTeamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       int32                  `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	NumberOfTeams int32                  `protobuf:"varint,2,opt,name=number_of_teams,json=numberOfTeams,proto3" json:"number_of_teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamsRequest) Reset() {
	*x = AddTeamsRequest{}
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamsRequest) ProtoMessage() {}

func (x *AddTeamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamsRequest.ProtoReflect.Descriptor instead.
func (*AddTeamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_team_proto_rawDescGZIP(), []int{5}
}

func (x *AddTeamsRequest) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *AddTeamsRequest) GetNumberOfTeams() int32 {
	if x != nil {
		return x.NumberOfTeams
	}
	return 0
}

type AddTeamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTeamsResponse) Reset() {
	*x = AddTeamsResponse{}
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTeamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTeamsResponse) ProtoMessage() {}

func (x *AddTeamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_participant_v1_team_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTeamsResponse.ProtoReflect.Descriptor instead.
func (*AddTeamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_participant_v1_team_proto_rawDescGZIP(), []int{6}
}

var File_proto_services_participant_v1_team_proto protoreflect.FileDescriptor

const file_proto_services_participant_v1_team_proto_rawDesc = "" +
	"\n" +
	"(proto/services/participant/v1/team.proto\x12\x17services.participant.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x11AddClassesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x05R\bcourseId\x12\x14\n" +
	"\x05names\x18\x02 \x03(\tR\x05names\"\x14\n" +
	"\x12AddClassesResponse\"\x80\x02\n" +
	"\x05Class\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\x05R\bcourseId\x12\x1f\n" +
	"\vcourse_name\x18\x04 \x01(\tR\n" +
	"courseName\x12\x1f\n" +
	"\vcourse_year\x18\x05 \x01(\x05R\n" +
	"courseYear\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\":\n" +
	"\x1bGetClassesByCourseIDRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\x05R\bcourseId\"X\n" +
	"\x1cGetClassesByCourseIDResponse\x128\n" +
	"\aclasses\x18\x01 \x03(\v2\x1e.services.participant.v1.ClassR\aclasses\"T\n" +
	"\x0fAddTeamsRequest\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\x05R\aclassId\x12&\n" +
	"\x0fnumber_of_teams\x18\x02 \x01(\x05R\rnumberOfTeams\"\x12\n" +
	"\x10AddTeamsResponse2\xdb\x02\n" +
	"\vTeamService\x12e\n" +
	"\n" +
	"AddClasses\x12*.services.participant.v1.AddClassesRequest\x1a+.services.participant.v1.AddClassesResponse\x12\x83\x01\n" +
	"\x14GetClassesByCourseID\x124.services.participant.v1.GetClassesByCourseIDRequest\x1a5.services.participant.v1.GetClassesByCourseIDResponse\x12_\n" +
	"\bAddTeams\x12(.services.participant.v1.AddTeamsRequest\x1a).services.participant.v1.AddTeamsResponseBKZIgithub.com/loanem-backend/protos/pb/services/participant/v1;participantv1b\x06proto3"

var (
	file_proto_services_participant_v1_team_proto_rawDescOnce sync.Once
	file_proto_services_participant_v1_team_proto_rawDescData []byte
)

func file_proto_services_participant_v1_team_proto_rawDescGZIP() []byte {
	file_proto_services_participant_v1_team_proto_rawDescOnce.Do(func() {
		file_proto_services_participant_v1_team_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_team_proto_rawDesc), len(file_proto_services_participant_v1_team_proto_rawDesc)))
	})
	return file_proto_services_participant_v1_team_proto_rawDescData
}

var file_proto_services_participant_v1_team_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_services_participant_v1_team_proto_goTypes = []any{
	(*AddClassesRequest)(nil),            // 0: services.participant.v1.AddClassesRequest
	(*AddClassesResponse)(nil),           // 1: services.participant.v1.AddClassesResponse
	(*Class)(nil),                        // 2: services.participant.v1.Class
	(*GetClassesByCourseIDRequest)(nil),  // 3: services.participant.v1.GetClassesByCourseIDRequest
	(*GetClassesByCourseIDResponse)(nil), // 4: services.participant.v1.GetClassesByCourseIDResponse
	(*AddTeamsRequest)(nil),              // 5: services.participant.v1.AddTeamsRequest
	(*AddTeamsResponse)(nil),             // 6: services.participant.v1.AddTeamsResponse
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_proto_services_participant_v1_team_proto_depIdxs = []int32{
	7, // 0: services.participant.v1.Class.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: services.participant.v1.Class.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: services.participant.v1.GetClassesByCourseIDResponse.classes:type_name -> services.participant.v1.Class
	0, // 3: services.participant.v1.TeamService.AddClasses:input_type -> services.participant.v1.AddClassesRequest
	3, // 4: services.participant.v1.TeamService.GetClassesByCourseID:input_type -> services.participant.v1.GetClassesByCourseIDRequest
	5, // 5: services.participant.v1.TeamService.AddTeams:input_type -> services.participant.v1.AddTeamsRequest
	1, // 6: services.participant.v1.TeamService.AddClasses:output_type -> services.participant.v1.AddClassesResponse
	4, // 7: services.participant.v1.TeamService.GetClassesByCourseID:output_type -> services.participant.v1.GetClassesByCourseIDResponse
	6, // 8: services.participant.v1.TeamService.AddTeams:output_type -> services.participant.v1.AddTeamsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_services_participant_v1_team_proto_init() }
func file_proto_services_participant_v1_team_proto_init() {
	if File_proto_services_participant_v1_team_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_participant_v1_team_proto_rawDesc), len(file_proto_services_participant_v1_team_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_participant_v1_team_proto_goTypes,
		DependencyIndexes: file_proto_services_participant_v1_team_proto_depIdxs,
		MessageInfos:      file_proto_services_participant_v1_team_proto_msgTypes,
	}.Build()
	File_proto_services_participant_v1_team_proto = out.File
	file_proto_services_participant_v1_team_proto_goTypes = nil
	file_proto_services_participant_v1_team_proto_depIdxs = nil
}
