syntax = "proto3";

package services.inventory.v1;

import "proto/google/type/date.proto";
import "google/protobuf/timestamp.proto";
import "proto/services/inventory/v1/toolkit.proto";

option go_package = "github.com/loanem-backend/protos/pb/services/inventory/v1;inventoryv1";

service LoanService {
    rpc AddLoan(AddLoanRequest) returns (AddLoanResponse);
    rpc SetLoanStatus(SetLoanStatusRequest) returns (SetLoanStatusResponse);
    rpc SetLoanNote(SetLoanNoteRequest) returns (SetLoanNoteResponse);

    rpc GetLoanByID(GetLoanByIDRequest) returns (GetLoanByIDResponse);
    rpc GetLoansByDate(GetLoansByDateRequest) returns (GetLoansByDateResponse);
    rpc GetLoansByTeamID(GetLoansByTeamIDRequest) returns (GetLoansByTeamIDResponse);
}

message AddLoanRequest {
    int32 toolkit_id = 1;
    string team_id = 2;
    string submitter_id = 3;
    google.type.Date date = 4;
    int32 session_number = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
}

message AddLoanResponse {
    string id = 1;
}

message SetLoanStatusRequest {
    string id = 1;
    string status = 2;
}

message SetLoanStatusResponse {}

message SetLoanNoteRequest {
    string id = 1;
    string note = 2;
}

message SetLoanNoteResponse {}

message Loan {
    string id = 1;
    Toolkit toolkit = 2;
    int32 team_number = 3;
    int32 class_id = 4;
    string class_name = 5;
    string submitter_nim = 6;
    string submitter_name = 7;
    google.type.Date date = 8;
    int32 session_number = 9;
    string status = 10;
    string note = 11;
    google.protobuf.Timestamp created_at = 12;
    google.protobuf.Timestamp updated_at = 13;
}

message GetLoanByIDRequest {
    string id = 1;
}

message GetLoanByIDResponse {
    Loan loan = 1;
}

message GetLoansByDateRequest {
    google.type.Date date = 1;
}

message GetLoansByDateResponse {
    repeated Loan loans = 1;
}

message GetLoansByTeamIDRequest {
    string team_id = 1;
}

message GetLoansByTeamIDResponse {
    repeated Loan loans = 1;
}
