// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/auth/v1/assistant.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAssistantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Period        int32                  `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssistantRequest) Reset() {
	*x = CreateAssistantRequest{}
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssistantRequest) ProtoMessage() {}

func (x *CreateAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssistantRequest.ProtoReflect.Descriptor instead.
func (*CreateAssistantRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_auth_v1_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAssistantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssistantRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateAssistantRequest) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

type CreateAssistantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssistantResponse) Reset() {
	*x = CreateAssistantResponse{}
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssistantResponse) ProtoMessage() {}

func (x *CreateAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssistantResponse.ProtoReflect.Descriptor instead.
func (*CreateAssistantResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_auth_v1_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAssistantResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetAssistantPasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OldPassword     string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	ConfirmPassword string                 `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetAssistantPasswordRequest) Reset() {
	*x = SetAssistantPasswordRequest{}
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAssistantPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAssistantPasswordRequest) ProtoMessage() {}

func (x *SetAssistantPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAssistantPasswordRequest.ProtoReflect.Descriptor instead.
func (*SetAssistantPasswordRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_auth_v1_assistant_proto_rawDescGZIP(), []int{2}
}

func (x *SetAssistantPasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *SetAssistantPasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *SetAssistantPasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

type SetAssistantPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAssistantPasswordResponse) Reset() {
	*x = SetAssistantPasswordResponse{}
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAssistantPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAssistantPasswordResponse) ProtoMessage() {}

func (x *SetAssistantPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAssistantPasswordResponse.ProtoReflect.Descriptor instead.
func (*SetAssistantPasswordResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_auth_v1_assistant_proto_rawDescGZIP(), []int{3}
}

type GetActiveAssistantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAssistantsRequest) Reset() {
	*x = GetActiveAssistantsRequest{}
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAssistantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAssistantsRequest) ProtoMessage() {}

func (x *GetActiveAssistantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAssistantsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveAssistantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_auth_v1_assistant_proto_rawDescGZIP(), []int{4}
}

type Assistant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Period        int32                  `protobuf:"varint,5,opt,name=period,proto3" json:"period,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assistant) Reset() {
	*x = Assistant{}
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assistant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assistant) ProtoMessage() {}

func (x *Assistant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assistant.ProtoReflect.Descriptor instead.
func (*Assistant) Descriptor() ([]byte, []int) {
	return file_proto_services_auth_v1_assistant_proto_rawDescGZIP(), []int{5}
}

func (x *Assistant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Assistant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Assistant) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Assistant) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Assistant) GetPeriod() int32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *Assistant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Assistant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetActiveAssistantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assistants    []*Assistant           `protobuf:"bytes,1,rep,name=assistants,proto3" json:"assistants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAssistantsResponse) Reset() {
	*x = GetActiveAssistantsResponse{}
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAssistantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAssistantsResponse) ProtoMessage() {}

func (x *GetActiveAssistantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_auth_v1_assistant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAssistantsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveAssistantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_auth_v1_assistant_proto_rawDescGZIP(), []int{6}
}

func (x *GetActiveAssistantsResponse) GetAssistants() []*Assistant {
	if x != nil {
		return x.Assistants
	}
	return nil
}

var File_proto_services_auth_v1_assistant_proto protoreflect.FileDescriptor

const file_proto_services_auth_v1_assistant_proto_rawDesc = "" +
	"\n" +
	"&proto/services/auth/v1/assistant.proto\x12\x10services.auth.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"Z\n" +
	"\x16CreateAssistantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x16\n" +
	"\x06period\x18\x03 \x01(\x05R\x06period\")\n" +
	"\x17CreateAssistantResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x8e\x01\n" +
	"\x1bSetAssistantPasswordRequest\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x03 \x01(\tR\x0fconfirmPassword\"\x1e\n" +
	"\x1cSetAssistantPasswordResponse\"\x1c\n" +
	"\x1aGetActiveAssistantsRequest\"\xeb\x01\n" +
	"\tAssistant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x16\n" +
	"\x06period\x18\x05 \x01(\x05R\x06period\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Z\n" +
	"\x1bGetActiveAssistantsResponse\x12;\n" +
	"\n" +
	"assistants\x18\x01 \x03(\v2\x1b.services.auth.v1.AssistantR\n" +
	"assistants2\xe5\x02\n" +
	"\x10AssistantService\x12f\n" +
	"\x0fCreateAssistant\x12(.services.auth.v1.CreateAssistantRequest\x1a).services.auth.v1.CreateAssistantResponse\x12u\n" +
	"\x14SetAssistantPassword\x12-.services.auth.v1.SetAssistantPasswordRequest\x1a..services.auth.v1.SetAssistantPasswordResponse\x12r\n" +
	"\x13GetActiveAssistants\x12,.services.auth.v1.GetActiveAssistantsRequest\x1a-.services.auth.v1.GetActiveAssistantsResponseB=Z;github.com/loanem-backend/protos/pb/services/auth/v1;authv1b\x06proto3"

var (
	file_proto_services_auth_v1_assistant_proto_rawDescOnce sync.Once
	file_proto_services_auth_v1_assistant_proto_rawDescData []byte
)

func file_proto_services_auth_v1_assistant_proto_rawDescGZIP() []byte {
	file_proto_services_auth_v1_assistant_proto_rawDescOnce.Do(func() {
		file_proto_services_auth_v1_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_auth_v1_assistant_proto_rawDesc), len(file_proto_services_auth_v1_assistant_proto_rawDesc)))
	})
	return file_proto_services_auth_v1_assistant_proto_rawDescData
}

var file_proto_services_auth_v1_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_services_auth_v1_assistant_proto_goTypes = []any{
	(*CreateAssistantRequest)(nil),       // 0: services.auth.v1.CreateAssistantRequest
	(*CreateAssistantResponse)(nil),      // 1: services.auth.v1.CreateAssistantResponse
	(*SetAssistantPasswordRequest)(nil),  // 2: services.auth.v1.SetAssistantPasswordRequest
	(*SetAssistantPasswordResponse)(nil), // 3: services.auth.v1.SetAssistantPasswordResponse
	(*GetActiveAssistantsRequest)(nil),   // 4: services.auth.v1.GetActiveAssistantsRequest
	(*Assistant)(nil),                    // 5: services.auth.v1.Assistant
	(*GetActiveAssistantsResponse)(nil),  // 6: services.auth.v1.GetActiveAssistantsResponse
	(*timestamppb.Timestamp)(nil),        // 7: google.protobuf.Timestamp
}
var file_proto_services_auth_v1_assistant_proto_depIdxs = []int32{
	7, // 0: services.auth.v1.Assistant.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: services.auth.v1.Assistant.updated_at:type_name -> google.protobuf.Timestamp
	5, // 2: services.auth.v1.GetActiveAssistantsResponse.assistants:type_name -> services.auth.v1.Assistant
	0, // 3: services.auth.v1.AssistantService.CreateAssistant:input_type -> services.auth.v1.CreateAssistantRequest
	2, // 4: services.auth.v1.AssistantService.SetAssistantPassword:input_type -> services.auth.v1.SetAssistantPasswordRequest
	4, // 5: services.auth.v1.AssistantService.GetActiveAssistants:input_type -> services.auth.v1.GetActiveAssistantsRequest
	1, // 6: services.auth.v1.AssistantService.CreateAssistant:output_type -> services.auth.v1.CreateAssistantResponse
	3, // 7: services.auth.v1.AssistantService.SetAssistantPassword:output_type -> services.auth.v1.SetAssistantPasswordResponse
	6, // 8: services.auth.v1.AssistantService.GetActiveAssistants:output_type -> services.auth.v1.GetActiveAssistantsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_services_auth_v1_assistant_proto_init() }
func file_proto_services_auth_v1_assistant_proto_init() {
	if File_proto_services_auth_v1_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_auth_v1_assistant_proto_rawDesc), len(file_proto_services_auth_v1_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_auth_v1_assistant_proto_goTypes,
		DependencyIndexes: file_proto_services_auth_v1_assistant_proto_depIdxs,
		MessageInfos:      file_proto_services_auth_v1_assistant_proto_msgTypes,
	}.Build()
	File_proto_services_auth_v1_assistant_proto = out.File
	file_proto_services_auth_v1_assistant_proto_goTypes = nil
	file_proto_services_auth_v1_assistant_proto_depIdxs = nil
}
