// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/services/auth/v1/assistant.proto

package authv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssistantService_CreateAssistant_FullMethodName      = "/services.auth.v1.AssistantService/CreateAssistant"
	AssistantService_SetAssistantPassword_FullMethodName = "/services.auth.v1.AssistantService/SetAssistantPassword"
	AssistantService_GetActiveAssistants_FullMethodName  = "/services.auth.v1.AssistantService/GetActiveAssistants"
)

// AssistantServiceClient is the client API for AssistantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssistantServiceClient interface {
	CreateAssistant(ctx context.Context, in *CreateAssistantRequest, opts ...grpc.CallOption) (*CreateAssistantResponse, error)
	SetAssistantPassword(ctx context.Context, in *SetAssistantPasswordRequest, opts ...grpc.CallOption) (*SetAssistantPasswordResponse, error)
	GetActiveAssistants(ctx context.Context, in *GetActiveAssistantsRequest, opts ...grpc.CallOption) (*GetActiveAssistantsResponse, error)
}

type assistantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssistantServiceClient(cc grpc.ClientConnInterface) AssistantServiceClient {
	return &assistantServiceClient{cc}
}

func (c *assistantServiceClient) CreateAssistant(ctx context.Context, in *CreateAssistantRequest, opts ...grpc.CallOption) (*CreateAssistantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssistantResponse)
	err := c.cc.Invoke(ctx, AssistantService_CreateAssistant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) SetAssistantPassword(ctx context.Context, in *SetAssistantPasswordRequest, opts ...grpc.CallOption) (*SetAssistantPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAssistantPasswordResponse)
	err := c.cc.Invoke(ctx, AssistantService_SetAssistantPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assistantServiceClient) GetActiveAssistants(ctx context.Context, in *GetActiveAssistantsRequest, opts ...grpc.CallOption) (*GetActiveAssistantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveAssistantsResponse)
	err := c.cc.Invoke(ctx, AssistantService_GetActiveAssistants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistantServiceServer is the server API for AssistantService service.
// All implementations must embed UnimplementedAssistantServiceServer
// for forward compatibility.
type AssistantServiceServer interface {
	CreateAssistant(context.Context, *CreateAssistantRequest) (*CreateAssistantResponse, error)
	SetAssistantPassword(context.Context, *SetAssistantPasswordRequest) (*SetAssistantPasswordResponse, error)
	GetActiveAssistants(context.Context, *GetActiveAssistantsRequest) (*GetActiveAssistantsResponse, error)
	mustEmbedUnimplementedAssistantServiceServer()
}

// UnimplementedAssistantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssistantServiceServer struct{}

func (UnimplementedAssistantServiceServer) CreateAssistant(context.Context, *CreateAssistantRequest) (*CreateAssistantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAssistant not implemented")
}
func (UnimplementedAssistantServiceServer) SetAssistantPassword(context.Context, *SetAssistantPasswordRequest) (*SetAssistantPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAssistantPassword not implemented")
}
func (UnimplementedAssistantServiceServer) GetActiveAssistants(context.Context, *GetActiveAssistantsRequest) (*GetActiveAssistantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveAssistants not implemented")
}
func (UnimplementedAssistantServiceServer) mustEmbedUnimplementedAssistantServiceServer() {}
func (UnimplementedAssistantServiceServer) testEmbeddedByValue()                          {}

// UnsafeAssistantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssistantServiceServer will
// result in compilation errors.
type UnsafeAssistantServiceServer interface {
	mustEmbedUnimplementedAssistantServiceServer()
}

func RegisterAssistantServiceServer(s grpc.ServiceRegistrar, srv AssistantServiceServer) {
	// If the following call panics, it indicates UnimplementedAssistantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssistantService_ServiceDesc, srv)
}

func _AssistantService_CreateAssistant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).CreateAssistant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_CreateAssistant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).CreateAssistant(ctx, req.(*CreateAssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_SetAssistantPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAssistantPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).SetAssistantPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_SetAssistantPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).SetAssistantPassword(ctx, req.(*SetAssistantPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssistantService_GetActiveAssistants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveAssistantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServiceServer).GetActiveAssistants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssistantService_GetActiveAssistants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServiceServer).GetActiveAssistants(ctx, req.(*GetActiveAssistantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssistantService_ServiceDesc is the grpc.ServiceDesc for AssistantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssistantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.auth.v1.AssistantService",
	HandlerType: (*AssistantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAssistant",
			Handler:    _AssistantService_CreateAssistant_Handler,
		},
		{
			MethodName: "SetAssistantPassword",
			Handler:    _AssistantService_SetAssistantPassword_Handler,
		},
		{
			MethodName: "GetActiveAssistants",
			Handler:    _AssistantService_GetActiveAssistants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services/auth/v1/assistant.proto",
}
