// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/services/inventory/v1/instrument.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstrumentService_AddInstrument_FullMethodName     = "/services.inventory.v1.InstrumentService/AddInstrument"
	InstrumentService_GetAllInstruments_FullMethodName = "/services.inventory.v1.InstrumentService/GetAllInstruments"
)

// InstrumentServiceClient is the client API for InstrumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InstrumentServiceClient interface {
	AddInstrument(ctx context.Context, in *AddInstrumentRequest, opts ...grpc.CallOption) (*AddInstrumentResponse, error)
	GetAllInstruments(ctx context.Context, in *GetAllInstrumentsRequest, opts ...grpc.CallOption) (*GetAllInstrumentsResponse, error)
}

type instrumentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstrumentServiceClient(cc grpc.ClientConnInterface) InstrumentServiceClient {
	return &instrumentServiceClient{cc}
}

func (c *instrumentServiceClient) AddInstrument(ctx context.Context, in *AddInstrumentRequest, opts ...grpc.CallOption) (*AddInstrumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddInstrumentResponse)
	err := c.cc.Invoke(ctx, InstrumentService_AddInstrument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *instrumentServiceClient) GetAllInstruments(ctx context.Context, in *GetAllInstrumentsRequest, opts ...grpc.CallOption) (*GetAllInstrumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllInstrumentsResponse)
	err := c.cc.Invoke(ctx, InstrumentService_GetAllInstruments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstrumentServiceServer is the server API for InstrumentService service.
// All implementations must embed UnimplementedInstrumentServiceServer
// for forward compatibility.
type InstrumentServiceServer interface {
	AddInstrument(context.Context, *AddInstrumentRequest) (*AddInstrumentResponse, error)
	GetAllInstruments(context.Context, *GetAllInstrumentsRequest) (*GetAllInstrumentsResponse, error)
	mustEmbedUnimplementedInstrumentServiceServer()
}

// UnimplementedInstrumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstrumentServiceServer struct{}

func (UnimplementedInstrumentServiceServer) AddInstrument(context.Context, *AddInstrumentRequest) (*AddInstrumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddInstrument not implemented")
}
func (UnimplementedInstrumentServiceServer) GetAllInstruments(context.Context, *GetAllInstrumentsRequest) (*GetAllInstrumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllInstruments not implemented")
}
func (UnimplementedInstrumentServiceServer) mustEmbedUnimplementedInstrumentServiceServer() {}
func (UnimplementedInstrumentServiceServer) testEmbeddedByValue()                           {}

// UnsafeInstrumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstrumentServiceServer will
// result in compilation errors.
type UnsafeInstrumentServiceServer interface {
	mustEmbedUnimplementedInstrumentServiceServer()
}

func RegisterInstrumentServiceServer(s grpc.ServiceRegistrar, srv InstrumentServiceServer) {
	// If the following call panics, it indicates UnimplementedInstrumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstrumentService_ServiceDesc, srv)
}

func _InstrumentService_AddInstrument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInstrumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).AddInstrument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_AddInstrument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).AddInstrument(ctx, req.(*AddInstrumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstrumentService_GetAllInstruments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllInstrumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstrumentServiceServer).GetAllInstruments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstrumentService_GetAllInstruments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstrumentServiceServer).GetAllInstruments(ctx, req.(*GetAllInstrumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstrumentService_ServiceDesc is the grpc.ServiceDesc for InstrumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstrumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.inventory.v1.InstrumentService",
	HandlerType: (*InstrumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddInstrument",
			Handler:    _InstrumentService_AddInstrument_Handler,
		},
		{
			MethodName: "GetAllInstruments",
			Handler:    _InstrumentService_GetAllInstruments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services/inventory/v1/instrument.proto",
}
