// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddInstrumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInstrumentRequest) Reset() {
	*x = AddInstrumentRequest{}
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInstrumentRequest) ProtoMessage() {}

func (x *AddInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInstrumentRequest.ProtoReflect.Descriptor instead.
func (*AddInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *AddInstrumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AddInstrumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddInstrumentResponse) Reset() {
	*x = AddInstrumentResponse{}
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddInstrumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddInstrumentResponse) ProtoMessage() {}

func (x *AddInstrumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddInstrumentResponse.ProtoReflect.Descriptor instead.
func (*AddInstrumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *AddInstrumentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Instrument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instrument) Reset() {
	*x = Instrument{}
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instrument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instrument) ProtoMessage() {}

func (x *Instrument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instrument.ProtoReflect.Descriptor instead.
func (*Instrument) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Instrument) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Instrument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllInstrumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInstrumentsRequest) Reset() {
	*x = GetAllInstrumentsRequest{}
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInstrumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInstrumentsRequest) ProtoMessage() {}

func (x *GetAllInstrumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInstrumentsRequest.ProtoReflect.Descriptor instead.
func (*GetAllInstrumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

type GetAllInstrumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruments   []*Instrument          `protobuf:"bytes,1,rep,name=instruments,proto3" json:"instruments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllInstrumentsResponse) Reset() {
	*x = GetAllInstrumentsResponse{}
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllInstrumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInstrumentsResponse) ProtoMessage() {}

func (x *GetAllInstrumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInstrumentsResponse.ProtoReflect.Descriptor instead.
func (*GetAllInstrumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllInstrumentsResponse) GetInstruments() []*Instrument {
	if x != nil {
		return x.Instruments
	}
	return nil
}

var File_proto_services_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_proto_services_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"+proto/services/inventory/v1/inventory.proto\x12\x15services.inventory.v1\"*\n" +
	"\x14AddInstrumentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"'\n" +
	"\x15AddInstrumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"0\n" +
	"\n" +
	"Instrument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x1a\n" +
	"\x18GetAllInstrumentsRequest\"`\n" +
	"\x19GetAllInstrumentsResponse\x12C\n" +
	"\vinstruments\x18\x01 \x03(\v2!.services.inventory.v1.InstrumentR\vinstruments2\xf6\x01\n" +
	"\x10InventoryService\x12j\n" +
	"\rAddInstrument\x12+.services.inventory.v1.AddInstrumentRequest\x1a,.services.inventory.v1.AddInstrumentResponse\x12v\n" +
	"\x11GetAllInstruments\x12/.services.inventory.v1.GetAllInstrumentsRequest\x1a0.services.inventory.v1.GetAllInstrumentsResponseBGZEgithub.com/loanem-backend/protos/pb/services/inventory/v1;inventoryv1b\x06proto3"

var (
	file_proto_services_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_proto_services_inventory_v1_inventory_proto_rawDescData []byte
)

func file_proto_services_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_proto_services_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_proto_services_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_inventory_proto_rawDesc), len(file_proto_services_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_proto_services_inventory_v1_inventory_proto_rawDescData
}

var file_proto_services_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_services_inventory_v1_inventory_proto_goTypes = []any{
	(*AddInstrumentRequest)(nil),      // 0: services.inventory.v1.AddInstrumentRequest
	(*AddInstrumentResponse)(nil),     // 1: services.inventory.v1.AddInstrumentResponse
	(*Instrument)(nil),                // 2: services.inventory.v1.Instrument
	(*GetAllInstrumentsRequest)(nil),  // 3: services.inventory.v1.GetAllInstrumentsRequest
	(*GetAllInstrumentsResponse)(nil), // 4: services.inventory.v1.GetAllInstrumentsResponse
}
var file_proto_services_inventory_v1_inventory_proto_depIdxs = []int32{
	2, // 0: services.inventory.v1.GetAllInstrumentsResponse.instruments:type_name -> services.inventory.v1.Instrument
	0, // 1: services.inventory.v1.InventoryService.AddInstrument:input_type -> services.inventory.v1.AddInstrumentRequest
	3, // 2: services.inventory.v1.InventoryService.GetAllInstruments:input_type -> services.inventory.v1.GetAllInstrumentsRequest
	1, // 3: services.inventory.v1.InventoryService.AddInstrument:output_type -> services.inventory.v1.AddInstrumentResponse
	4, // 4: services.inventory.v1.InventoryService.GetAllInstruments:output_type -> services.inventory.v1.GetAllInstrumentsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_services_inventory_v1_inventory_proto_init() }
func file_proto_services_inventory_v1_inventory_proto_init() {
	if File_proto_services_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_inventory_proto_rawDesc), len(file_proto_services_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_proto_services_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_proto_services_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_proto_services_inventory_v1_inventory_proto = out.File
	file_proto_services_inventory_v1_inventory_proto_goTypes = nil
	file_proto_services_inventory_v1_inventory_proto_depIdxs = nil
}
