// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/inventory/v1/loan.proto

package inventoryv1

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLoanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolkitId     int32                  `protobuf:"varint,1,opt,name=toolkit_id,json=toolkitId,proto3" json:"toolkit_id,omitempty"`
	TeamId        string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SubmitterId   string                 `protobuf:"bytes,3,opt,name=submitter_id,json=submitterId,proto3" json:"submitter_id,omitempty"`
	Date          *date.Date             `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	SessionNumber int32                  `protobuf:"varint,5,opt,name=session_number,json=sessionNumber,proto3" json:"session_number,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLoanRequest) Reset() {
	*x = AddLoanRequest{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLoanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLoanRequest) ProtoMessage() {}

func (x *AddLoanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLoanRequest.ProtoReflect.Descriptor instead.
func (*AddLoanRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{0}
}

func (x *AddLoanRequest) GetToolkitId() int32 {
	if x != nil {
		return x.ToolkitId
	}
	return 0
}

func (x *AddLoanRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *AddLoanRequest) GetSubmitterId() string {
	if x != nil {
		return x.SubmitterId
	}
	return ""
}

func (x *AddLoanRequest) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *AddLoanRequest) GetSessionNumber() int32 {
	if x != nil {
		return x.SessionNumber
	}
	return 0
}

func (x *AddLoanRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AddLoanRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type AddLoanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLoanResponse) Reset() {
	*x = AddLoanResponse{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLoanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLoanResponse) ProtoMessage() {}

func (x *AddLoanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLoanResponse.ProtoReflect.Descriptor instead.
func (*AddLoanResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{1}
}

func (x *AddLoanResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SetLoanStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoanStatusRequest) Reset() {
	*x = SetLoanStatusRequest{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoanStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoanStatusRequest) ProtoMessage() {}

func (x *SetLoanStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoanStatusRequest.ProtoReflect.Descriptor instead.
func (*SetLoanStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{2}
}

func (x *SetLoanStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetLoanStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SetLoanStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoanStatusResponse) Reset() {
	*x = SetLoanStatusResponse{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoanStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoanStatusResponse) ProtoMessage() {}

func (x *SetLoanStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoanStatusResponse.ProtoReflect.Descriptor instead.
func (*SetLoanStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{3}
}

type SetLoanNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoanNoteRequest) Reset() {
	*x = SetLoanNoteRequest{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoanNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoanNoteRequest) ProtoMessage() {}

func (x *SetLoanNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoanNoteRequest.ProtoReflect.Descriptor instead.
func (*SetLoanNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{4}
}

func (x *SetLoanNoteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SetLoanNoteRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type SetLoanNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLoanNoteResponse) Reset() {
	*x = SetLoanNoteResponse{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLoanNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLoanNoteResponse) ProtoMessage() {}

func (x *SetLoanNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLoanNoteResponse.ProtoReflect.Descriptor instead.
func (*SetLoanNoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{5}
}

type Loan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Toolkit       *Toolkit               `protobuf:"bytes,2,opt,name=toolkit,proto3" json:"toolkit,omitempty"`
	TeamNumber    int32                  `protobuf:"varint,3,opt,name=team_number,json=teamNumber,proto3" json:"team_number,omitempty"`
	ClassId       int32                  `protobuf:"varint,4,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName     string                 `protobuf:"bytes,5,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	SubmitterNim  string                 `protobuf:"bytes,6,opt,name=submitter_nim,json=submitterNim,proto3" json:"submitter_nim,omitempty"`
	SubmitterName string                 `protobuf:"bytes,7,opt,name=submitter_name,json=submitterName,proto3" json:"submitter_name,omitempty"`
	Date          *date.Date             `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	SessionNumber int32                  `protobuf:"varint,9,opt,name=session_number,json=sessionNumber,proto3" json:"session_number,omitempty"`
	Status        string                 `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Note          string                 `protobuf:"bytes,11,opt,name=note,proto3" json:"note,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loan) Reset() {
	*x = Loan{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loan) ProtoMessage() {}

func (x *Loan) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loan.ProtoReflect.Descriptor instead.
func (*Loan) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{6}
}

func (x *Loan) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Loan) GetToolkit() *Toolkit {
	if x != nil {
		return x.Toolkit
	}
	return nil
}

func (x *Loan) GetTeamNumber() int32 {
	if x != nil {
		return x.TeamNumber
	}
	return 0
}

func (x *Loan) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *Loan) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *Loan) GetSubmitterNim() string {
	if x != nil {
		return x.SubmitterNim
	}
	return ""
}

func (x *Loan) GetSubmitterName() string {
	if x != nil {
		return x.SubmitterName
	}
	return ""
}

func (x *Loan) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Loan) GetSessionNumber() int32 {
	if x != nil {
		return x.SessionNumber
	}
	return 0
}

func (x *Loan) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Loan) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Loan) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Loan) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLoanByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanByIDRequest) Reset() {
	*x = GetLoanByIDRequest{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanByIDRequest) ProtoMessage() {}

func (x *GetLoanByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLoanByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{7}
}

func (x *GetLoanByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetLoanByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loan          *Loan                  `protobuf:"bytes,1,opt,name=loan,proto3" json:"loan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoanByIDResponse) Reset() {
	*x = GetLoanByIDResponse{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoanByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoanByIDResponse) ProtoMessage() {}

func (x *GetLoanByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoanByIDResponse.ProtoReflect.Descriptor instead.
func (*GetLoanByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{8}
}

func (x *GetLoanByIDResponse) GetLoan() *Loan {
	if x != nil {
		return x.Loan
	}
	return nil
}

type GetLoansByDateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *date.Date             `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoansByDateRequest) Reset() {
	*x = GetLoansByDateRequest{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoansByDateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoansByDateRequest) ProtoMessage() {}

func (x *GetLoansByDateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoansByDateRequest.ProtoReflect.Descriptor instead.
func (*GetLoansByDateRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{9}
}

func (x *GetLoansByDateRequest) GetDate() *date.Date {
	if x != nil {
		return x.Date
	}
	return nil
}

type GetLoansByDateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loans         []*Loan                `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoansByDateResponse) Reset() {
	*x = GetLoansByDateResponse{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoansByDateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoansByDateResponse) ProtoMessage() {}

func (x *GetLoansByDateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoansByDateResponse.ProtoReflect.Descriptor instead.
func (*GetLoansByDateResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{10}
}

func (x *GetLoansByDateResponse) GetLoans() []*Loan {
	if x != nil {
		return x.Loans
	}
	return nil
}

type GetLoansByTeamIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoansByTeamIDRequest) Reset() {
	*x = GetLoansByTeamIDRequest{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoansByTeamIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoansByTeamIDRequest) ProtoMessage() {}

func (x *GetLoansByTeamIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoansByTeamIDRequest.ProtoReflect.Descriptor instead.
func (*GetLoansByTeamIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{11}
}

func (x *GetLoansByTeamIDRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

type GetLoansByTeamIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loans         []*Loan                `protobuf:"bytes,1,rep,name=loans,proto3" json:"loans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoansByTeamIDResponse) Reset() {
	*x = GetLoansByTeamIDResponse{}
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoansByTeamIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoansByTeamIDResponse) ProtoMessage() {}

func (x *GetLoansByTeamIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_loan_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoansByTeamIDResponse.ProtoReflect.Descriptor instead.
func (*GetLoansByTeamIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_loan_proto_rawDescGZIP(), []int{12}
}

func (x *GetLoansByTeamIDResponse) GetLoans() []*Loan {
	if x != nil {
		return x.Loans
	}
	return nil
}

var File_proto_services_inventory_v1_loan_proto protoreflect.FileDescriptor

const file_proto_services_inventory_v1_loan_proto_rawDesc = "" +
	"\n" +
	"&proto/services/inventory/v1/loan.proto\x12\x15services.inventory.v1\x1a\x1cproto/google/type/date.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a)proto/services/inventory/v1/toolkit.proto\"\xaf\x02\n" +
	"\x0eAddLoanRequest\x12\x1d\n" +
	"\n" +
	"toolkit_id\x18\x01 \x01(\x05R\ttoolkitId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12!\n" +
	"\fsubmitter_id\x18\x03 \x01(\tR\vsubmitterId\x12%\n" +
	"\x04date\x18\x04 \x01(\v2\x11.google.type.DateR\x04date\x12%\n" +
	"\x0esession_number\x18\x05 \x01(\x05R\rsessionNumber\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"!\n" +
	"\x0fAddLoanResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x14SetLoanStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x17\n" +
	"\x15SetLoanStatusResponse\"8\n" +
	"\x12SetLoanNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note\"\x15\n" +
	"\x13SetLoanNoteResponse\"\xe7\x03\n" +
	"\x04Loan\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\atoolkit\x18\x02 \x01(\v2\x1e.services.inventory.v1.ToolkitR\atoolkit\x12\x1f\n" +
	"\vteam_number\x18\x03 \x01(\x05R\n" +
	"teamNumber\x12\x19\n" +
	"\bclass_id\x18\x04 \x01(\x05R\aclassId\x12\x1d\n" +
	"\n" +
	"class_name\x18\x05 \x01(\tR\tclassName\x12#\n" +
	"\rsubmitter_nim\x18\x06 \x01(\tR\fsubmitterNim\x12%\n" +
	"\x0esubmitter_name\x18\a \x01(\tR\rsubmitterName\x12%\n" +
	"\x04date\x18\b \x01(\v2\x11.google.type.DateR\x04date\x12%\n" +
	"\x0esession_number\x18\t \x01(\x05R\rsessionNumber\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"$\n" +
	"\x12GetLoanByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"F\n" +
	"\x13GetLoanByIDResponse\x12/\n" +
	"\x04loan\x18\x01 \x01(\v2\x1b.services.inventory.v1.LoanR\x04loan\">\n" +
	"\x15GetLoansByDateRequest\x12%\n" +
	"\x04date\x18\x01 \x01(\v2\x11.google.type.DateR\x04date\"K\n" +
	"\x16GetLoansByDateResponse\x121\n" +
	"\x05loans\x18\x01 \x03(\v2\x1b.services.inventory.v1.LoanR\x05loans\"2\n" +
	"\x17GetLoansByTeamIDRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"M\n" +
	"\x18GetLoansByTeamIDResponse\x121\n" +
	"\x05loans\x18\x01 \x03(\v2\x1b.services.inventory.v1.LoanR\x05loans2\x83\x05\n" +
	"\vLoanService\x12X\n" +
	"\aAddLoan\x12%.services.inventory.v1.AddLoanRequest\x1a&.services.inventory.v1.AddLoanResponse\x12j\n" +
	"\rSetLoanStatus\x12+.services.inventory.v1.SetLoanStatusRequest\x1a,.services.inventory.v1.SetLoanStatusResponse\x12d\n" +
	"\vSetLoanNote\x12).services.inventory.v1.SetLoanNoteRequest\x1a*.services.inventory.v1.SetLoanNoteResponse\x12d\n" +
	"\vGetLoanByID\x12).services.inventory.v1.GetLoanByIDRequest\x1a*.services.inventory.v1.GetLoanByIDResponse\x12m\n" +
	"\x0eGetLoansByDate\x12,.services.inventory.v1.GetLoansByDateRequest\x1a-.services.inventory.v1.GetLoansByDateResponse\x12s\n" +
	"\x10GetLoansByTeamID\x12..services.inventory.v1.GetLoansByTeamIDRequest\x1a/.services.inventory.v1.GetLoansByTeamIDResponseBGZEgithub.com/loanem-backend/protos/pb/services/inventory/v1;inventoryv1b\x06proto3"

var (
	file_proto_services_inventory_v1_loan_proto_rawDescOnce sync.Once
	file_proto_services_inventory_v1_loan_proto_rawDescData []byte
)

func file_proto_services_inventory_v1_loan_proto_rawDescGZIP() []byte {
	file_proto_services_inventory_v1_loan_proto_rawDescOnce.Do(func() {
		file_proto_services_inventory_v1_loan_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_loan_proto_rawDesc), len(file_proto_services_inventory_v1_loan_proto_rawDesc)))
	})
	return file_proto_services_inventory_v1_loan_proto_rawDescData
}

var file_proto_services_inventory_v1_loan_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_services_inventory_v1_loan_proto_goTypes = []any{
	(*AddLoanRequest)(nil),           // 0: services.inventory.v1.AddLoanRequest
	(*AddLoanResponse)(nil),          // 1: services.inventory.v1.AddLoanResponse
	(*SetLoanStatusRequest)(nil),     // 2: services.inventory.v1.SetLoanStatusRequest
	(*SetLoanStatusResponse)(nil),    // 3: services.inventory.v1.SetLoanStatusResponse
	(*SetLoanNoteRequest)(nil),       // 4: services.inventory.v1.SetLoanNoteRequest
	(*SetLoanNoteResponse)(nil),      // 5: services.inventory.v1.SetLoanNoteResponse
	(*Loan)(nil),                     // 6: services.inventory.v1.Loan
	(*GetLoanByIDRequest)(nil),       // 7: services.inventory.v1.GetLoanByIDRequest
	(*GetLoanByIDResponse)(nil),      // 8: services.inventory.v1.GetLoanByIDResponse
	(*GetLoansByDateRequest)(nil),    // 9: services.inventory.v1.GetLoansByDateRequest
	(*GetLoansByDateResponse)(nil),   // 10: services.inventory.v1.GetLoansByDateResponse
	(*GetLoansByTeamIDRequest)(nil),  // 11: services.inventory.v1.GetLoansByTeamIDRequest
	(*GetLoansByTeamIDResponse)(nil), // 12: services.inventory.v1.GetLoansByTeamIDResponse
	(*date.Date)(nil),                // 13: google.type.Date
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*Toolkit)(nil),                  // 15: services.inventory.v1.Toolkit
}
var file_proto_services_inventory_v1_loan_proto_depIdxs = []int32{
	13, // 0: services.inventory.v1.AddLoanRequest.date:type_name -> google.type.Date
	14, // 1: services.inventory.v1.AddLoanRequest.created_at:type_name -> google.protobuf.Timestamp
	14, // 2: services.inventory.v1.AddLoanRequest.updated_at:type_name -> google.protobuf.Timestamp
	15, // 3: services.inventory.v1.Loan.toolkit:type_name -> services.inventory.v1.Toolkit
	13, // 4: services.inventory.v1.Loan.date:type_name -> google.type.Date
	14, // 5: services.inventory.v1.Loan.created_at:type_name -> google.protobuf.Timestamp
	14, // 6: services.inventory.v1.Loan.updated_at:type_name -> google.protobuf.Timestamp
	6,  // 7: services.inventory.v1.GetLoanByIDResponse.loan:type_name -> services.inventory.v1.Loan
	13, // 8: services.inventory.v1.GetLoansByDateRequest.date:type_name -> google.type.Date
	6,  // 9: services.inventory.v1.GetLoansByDateResponse.loans:type_name -> services.inventory.v1.Loan
	6,  // 10: services.inventory.v1.GetLoansByTeamIDResponse.loans:type_name -> services.inventory.v1.Loan
	0,  // 11: services.inventory.v1.LoanService.AddLoan:input_type -> services.inventory.v1.AddLoanRequest
	2,  // 12: services.inventory.v1.LoanService.SetLoanStatus:input_type -> services.inventory.v1.SetLoanStatusRequest
	4,  // 13: services.inventory.v1.LoanService.SetLoanNote:input_type -> services.inventory.v1.SetLoanNoteRequest
	7,  // 14: services.inventory.v1.LoanService.GetLoanByID:input_type -> services.inventory.v1.GetLoanByIDRequest
	9,  // 15: services.inventory.v1.LoanService.GetLoansByDate:input_type -> services.inventory.v1.GetLoansByDateRequest
	11, // 16: services.inventory.v1.LoanService.GetLoansByTeamID:input_type -> services.inventory.v1.GetLoansByTeamIDRequest
	1,  // 17: services.inventory.v1.LoanService.AddLoan:output_type -> services.inventory.v1.AddLoanResponse
	3,  // 18: services.inventory.v1.LoanService.SetLoanStatus:output_type -> services.inventory.v1.SetLoanStatusResponse
	5,  // 19: services.inventory.v1.LoanService.SetLoanNote:output_type -> services.inventory.v1.SetLoanNoteResponse
	8,  // 20: services.inventory.v1.LoanService.GetLoanByID:output_type -> services.inventory.v1.GetLoanByIDResponse
	10, // 21: services.inventory.v1.LoanService.GetLoansByDate:output_type -> services.inventory.v1.GetLoansByDateResponse
	12, // 22: services.inventory.v1.LoanService.GetLoansByTeamID:output_type -> services.inventory.v1.GetLoansByTeamIDResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_services_inventory_v1_loan_proto_init() }
func file_proto_services_inventory_v1_loan_proto_init() {
	if File_proto_services_inventory_v1_loan_proto != nil {
		return
	}
	file_proto_services_inventory_v1_toolkit_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_loan_proto_rawDesc), len(file_proto_services_inventory_v1_loan_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_inventory_v1_loan_proto_goTypes,
		DependencyIndexes: file_proto_services_inventory_v1_loan_proto_depIdxs,
		MessageInfos:      file_proto_services_inventory_v1_loan_proto_msgTypes,
	}.Build()
	File_proto_services_inventory_v1_loan_proto = out.File
	file_proto_services_inventory_v1_loan_proto_goTypes = nil
	file_proto_services_inventory_v1_loan_proto_depIdxs = nil
}
