// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/services/inventory/v1/loan.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LoanService_AddLoan_FullMethodName          = "/services.inventory.v1.LoanService/AddLoan"
	LoanService_SetLoanStatus_FullMethodName    = "/services.inventory.v1.LoanService/SetLoanStatus"
	LoanService_SetLoanNote_FullMethodName      = "/services.inventory.v1.LoanService/SetLoanNote"
	LoanService_GetLoanByID_FullMethodName      = "/services.inventory.v1.LoanService/GetLoanByID"
	LoanService_GetLoansByDate_FullMethodName   = "/services.inventory.v1.LoanService/GetLoansByDate"
	LoanService_GetLoansByTeamID_FullMethodName = "/services.inventory.v1.LoanService/GetLoansByTeamID"
)

// LoanServiceClient is the client API for LoanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoanServiceClient interface {
	AddLoan(ctx context.Context, in *AddLoanRequest, opts ...grpc.CallOption) (*AddLoanResponse, error)
	SetLoanStatus(ctx context.Context, in *SetLoanStatusRequest, opts ...grpc.CallOption) (*SetLoanStatusResponse, error)
	SetLoanNote(ctx context.Context, in *SetLoanNoteRequest, opts ...grpc.CallOption) (*SetLoanNoteResponse, error)
	GetLoanByID(ctx context.Context, in *GetLoanByIDRequest, opts ...grpc.CallOption) (*GetLoanByIDResponse, error)
	GetLoansByDate(ctx context.Context, in *GetLoansByDateRequest, opts ...grpc.CallOption) (*GetLoansByDateResponse, error)
	GetLoansByTeamID(ctx context.Context, in *GetLoansByTeamIDRequest, opts ...grpc.CallOption) (*GetLoansByTeamIDResponse, error)
}

type loanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoanServiceClient(cc grpc.ClientConnInterface) LoanServiceClient {
	return &loanServiceClient{cc}
}

func (c *loanServiceClient) AddLoan(ctx context.Context, in *AddLoanRequest, opts ...grpc.CallOption) (*AddLoanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddLoanResponse)
	err := c.cc.Invoke(ctx, LoanService_AddLoan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) SetLoanStatus(ctx context.Context, in *SetLoanStatusRequest, opts ...grpc.CallOption) (*SetLoanStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLoanStatusResponse)
	err := c.cc.Invoke(ctx, LoanService_SetLoanStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) SetLoanNote(ctx context.Context, in *SetLoanNoteRequest, opts ...grpc.CallOption) (*SetLoanNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLoanNoteResponse)
	err := c.cc.Invoke(ctx, LoanService_SetLoanNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoanByID(ctx context.Context, in *GetLoanByIDRequest, opts ...grpc.CallOption) (*GetLoanByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoanByIDResponse)
	err := c.cc.Invoke(ctx, LoanService_GetLoanByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoansByDate(ctx context.Context, in *GetLoansByDateRequest, opts ...grpc.CallOption) (*GetLoansByDateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoansByDateResponse)
	err := c.cc.Invoke(ctx, LoanService_GetLoansByDate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loanServiceClient) GetLoansByTeamID(ctx context.Context, in *GetLoansByTeamIDRequest, opts ...grpc.CallOption) (*GetLoansByTeamIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoansByTeamIDResponse)
	err := c.cc.Invoke(ctx, LoanService_GetLoansByTeamID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoanServiceServer is the server API for LoanService service.
// All implementations must embed UnimplementedLoanServiceServer
// for forward compatibility.
type LoanServiceServer interface {
	AddLoan(context.Context, *AddLoanRequest) (*AddLoanResponse, error)
	SetLoanStatus(context.Context, *SetLoanStatusRequest) (*SetLoanStatusResponse, error)
	SetLoanNote(context.Context, *SetLoanNoteRequest) (*SetLoanNoteResponse, error)
	GetLoanByID(context.Context, *GetLoanByIDRequest) (*GetLoanByIDResponse, error)
	GetLoansByDate(context.Context, *GetLoansByDateRequest) (*GetLoansByDateResponse, error)
	GetLoansByTeamID(context.Context, *GetLoansByTeamIDRequest) (*GetLoansByTeamIDResponse, error)
	mustEmbedUnimplementedLoanServiceServer()
}

// UnimplementedLoanServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLoanServiceServer struct{}

func (UnimplementedLoanServiceServer) AddLoan(context.Context, *AddLoanRequest) (*AddLoanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddLoan not implemented")
}
func (UnimplementedLoanServiceServer) SetLoanStatus(context.Context, *SetLoanStatusRequest) (*SetLoanStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLoanStatus not implemented")
}
func (UnimplementedLoanServiceServer) SetLoanNote(context.Context, *SetLoanNoteRequest) (*SetLoanNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLoanNote not implemented")
}
func (UnimplementedLoanServiceServer) GetLoanByID(context.Context, *GetLoanByIDRequest) (*GetLoanByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoanByID not implemented")
}
func (UnimplementedLoanServiceServer) GetLoansByDate(context.Context, *GetLoansByDateRequest) (*GetLoansByDateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoansByDate not implemented")
}
func (UnimplementedLoanServiceServer) GetLoansByTeamID(context.Context, *GetLoansByTeamIDRequest) (*GetLoansByTeamIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoansByTeamID not implemented")
}
func (UnimplementedLoanServiceServer) mustEmbedUnimplementedLoanServiceServer() {}
func (UnimplementedLoanServiceServer) testEmbeddedByValue()                     {}

// UnsafeLoanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoanServiceServer will
// result in compilation errors.
type UnsafeLoanServiceServer interface {
	mustEmbedUnimplementedLoanServiceServer()
}

func RegisterLoanServiceServer(s grpc.ServiceRegistrar, srv LoanServiceServer) {
	// If the following call panics, it indicates UnimplementedLoanServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LoanService_ServiceDesc, srv)
}

func _LoanService_AddLoan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddLoanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).AddLoan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_AddLoan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).AddLoan(ctx, req.(*AddLoanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_SetLoanStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoanStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).SetLoanStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_SetLoanStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).SetLoanStatus(ctx, req.(*SetLoanStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_SetLoanNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLoanNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).SetLoanNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_SetLoanNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).SetLoanNote(ctx, req.(*SetLoanNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoanByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoanByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoanByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoanByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoanByID(ctx, req.(*GetLoanByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoansByDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoansByDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoansByDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoansByDate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoansByDate(ctx, req.(*GetLoansByDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoanService_GetLoansByTeamID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoansByTeamIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoanServiceServer).GetLoansByTeamID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoanService_GetLoansByTeamID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoanServiceServer).GetLoansByTeamID(ctx, req.(*GetLoansByTeamIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoanService_ServiceDesc is the grpc.ServiceDesc for LoanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.inventory.v1.LoanService",
	HandlerType: (*LoanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLoan",
			Handler:    _LoanService_AddLoan_Handler,
		},
		{
			MethodName: "SetLoanStatus",
			Handler:    _LoanService_SetLoanStatus_Handler,
		},
		{
			MethodName: "SetLoanNote",
			Handler:    _LoanService_SetLoanNote_Handler,
		},
		{
			MethodName: "GetLoanByID",
			Handler:    _LoanService_GetLoanByID_Handler,
		},
		{
			MethodName: "GetLoansByDate",
			Handler:    _LoanService_GetLoansByDate_Handler,
		},
		{
			MethodName: "GetLoansByTeamID",
			Handler:    _LoanService_GetLoansByTeamID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services/inventory/v1/loan.proto",
}
