// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/inventory/v1/toolkit.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToolkitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KitName       string                 `protobuf:"bytes,1,opt,name=kit_name,json=kitName,proto3" json:"kit_name,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToolkitRequest) Reset() {
	*x = AddToolkitRequest{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToolkitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToolkitRequest) ProtoMessage() {}

func (x *AddToolkitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToolkitRequest.ProtoReflect.Descriptor instead.
func (*AddToolkitRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{0}
}

func (x *AddToolkitRequest) GetKitName() string {
	if x != nil {
		return x.KitName
	}
	return ""
}

func (x *AddToolkitRequest) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AddToolkitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToolkitResponse) Reset() {
	*x = AddToolkitResponse{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToolkitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToolkitResponse) ProtoMessage() {}

func (x *AddToolkitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToolkitResponse.ProtoReflect.Descriptor instead.
func (*AddToolkitResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{1}
}

func (x *AddToolkitResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Toolkit struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	KitName         string                 `protobuf:"bytes,2,opt,name=kit_name,json=kitName,proto3" json:"kit_name,omitempty"`
	TotalCount      int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	OutOfOrderCount int32                  `protobuf:"varint,4,opt,name=out_of_order_count,json=outOfOrderCount,proto3" json:"out_of_order_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Toolkit) Reset() {
	*x = Toolkit{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toolkit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toolkit) ProtoMessage() {}

func (x *Toolkit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toolkit.ProtoReflect.Descriptor instead.
func (*Toolkit) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{2}
}

func (x *Toolkit) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Toolkit) GetKitName() string {
	if x != nil {
		return x.KitName
	}
	return ""
}

func (x *Toolkit) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Toolkit) GetOutOfOrderCount() int32 {
	if x != nil {
		return x.OutOfOrderCount
	}
	return 0
}

func (x *Toolkit) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Toolkit) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetAllToolkitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToolkitsRequest) Reset() {
	*x = GetAllToolkitsRequest{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToolkitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToolkitsRequest) ProtoMessage() {}

func (x *GetAllToolkitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToolkitsRequest.ProtoReflect.Descriptor instead.
func (*GetAllToolkitsRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{3}
}

type GetAllToolkitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toolkits      []*Toolkit             `protobuf:"bytes,1,rep,name=toolkits,proto3" json:"toolkits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllToolkitsResponse) Reset() {
	*x = GetAllToolkitsResponse{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllToolkitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllToolkitsResponse) ProtoMessage() {}

func (x *GetAllToolkitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllToolkitsResponse.ProtoReflect.Descriptor instead.
func (*GetAllToolkitsResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllToolkitsResponse) GetToolkits() []*Toolkit {
	if x != nil {
		return x.Toolkits
	}
	return nil
}

type SetToolkitCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolkitId     int32                  `protobuf:"varint,1,opt,name=toolkit_id,json=toolkitId,proto3" json:"toolkit_id,omitempty"`
	CourseId      int32                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToolkitCourseIDRequest) Reset() {
	*x = SetToolkitCourseIDRequest{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToolkitCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToolkitCourseIDRequest) ProtoMessage() {}

func (x *SetToolkitCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToolkitCourseIDRequest.ProtoReflect.Descriptor instead.
func (*SetToolkitCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{5}
}

func (x *SetToolkitCourseIDRequest) GetToolkitId() int32 {
	if x != nil {
		return x.ToolkitId
	}
	return 0
}

func (x *SetToolkitCourseIDRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type SetToolkitCourseIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToolkitCourseIDResponse) Reset() {
	*x = SetToolkitCourseIDResponse{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToolkitCourseIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToolkitCourseIDResponse) ProtoMessage() {}

func (x *SetToolkitCourseIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToolkitCourseIDResponse.ProtoReflect.Descriptor instead.
func (*SetToolkitCourseIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{6}
}

type AddToolkitInstrumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolkitId     int32                  `protobuf:"varint,1,opt,name=toolkit_id,json=toolkitId,proto3" json:"toolkit_id,omitempty"`
	InstrumentId  int32                  `protobuf:"varint,2,opt,name=instrument_id,json=instrumentId,proto3" json:"instrument_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToolkitInstrumentRequest) Reset() {
	*x = AddToolkitInstrumentRequest{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToolkitInstrumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToolkitInstrumentRequest) ProtoMessage() {}

func (x *AddToolkitInstrumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToolkitInstrumentRequest.ProtoReflect.Descriptor instead.
func (*AddToolkitInstrumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{7}
}

func (x *AddToolkitInstrumentRequest) GetToolkitId() int32 {
	if x != nil {
		return x.ToolkitId
	}
	return 0
}

func (x *AddToolkitInstrumentRequest) GetInstrumentId() int32 {
	if x != nil {
		return x.InstrumentId
	}
	return 0
}

type AddToolkitInstrumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToolkitInstrumentResponse) Reset() {
	*x = AddToolkitInstrumentResponse{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToolkitInstrumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToolkitInstrumentResponse) ProtoMessage() {}

func (x *AddToolkitInstrumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToolkitInstrumentResponse.ProtoReflect.Descriptor instead.
func (*AddToolkitInstrumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{8}
}

var File_proto_services_inventory_v1_toolkit_proto protoreflect.FileDescriptor

const file_proto_services_inventory_v1_toolkit_proto_rawDesc = "" +
	"\n" +
	")proto/services/inventory/v1/toolkit.proto\x12\x15services.inventory.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"O\n" +
	"\x11AddToolkitRequest\x12\x19\n" +
	"\bkit_name\x18\x01 \x01(\tR\akitName\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"$\n" +
	"\x12AddToolkitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xf8\x01\n" +
	"\aToolkit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\bkit_name\x18\x02 \x01(\tR\akitName\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12+\n" +
	"\x12out_of_order_count\x18\x04 \x01(\x05R\x0foutOfOrderCount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x17\n" +
	"\x15GetAllToolkitsRequest\"T\n" +
	"\x16GetAllToolkitsResponse\x12:\n" +
	"\btoolkits\x18\x01 \x03(\v2\x1e.services.inventory.v1.ToolkitR\btoolkits\"W\n" +
	"\x19SetToolkitCourseIDRequest\x12\x1d\n" +
	"\n" +
	"toolkit_id\x18\x01 \x01(\x05R\ttoolkitId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x05R\bcourseId\"\x1c\n" +
	"\x1aSetToolkitCourseIDResponse\"a\n" +
	"\x1bAddToolkitInstrumentRequest\x12\x1d\n" +
	"\n" +
	"toolkit_id\x18\x01 \x01(\x05R\ttoolkitId\x12#\n" +
	"\rinstrument_id\x18\x02 \x01(\x05R\finstrumentId\"\x1e\n" +
	"\x1cAddToolkitInstrumentResponse2\xde\x03\n" +
	"\x0eToolkitService\x12a\n" +
	"\n" +
	"AddToolkit\x12(.services.inventory.v1.AddToolkitRequest\x1a).services.inventory.v1.AddToolkitResponse\x12m\n" +
	"\x0eGetAllToolkits\x12,.services.inventory.v1.GetAllToolkitsRequest\x1a-.services.inventory.v1.GetAllToolkitsResponse\x12\x7f\n" +
	"\x14AddToolkitInstrument\x122.services.inventory.v1.AddToolkitInstrumentRequest\x1a3.services.inventory.v1.AddToolkitInstrumentResponse\x12y\n" +
	"\x12SetToolkitCourseID\x120.services.inventory.v1.SetToolkitCourseIDRequest\x1a1.services.inventory.v1.SetToolkitCourseIDResponseBGZEgithub.com/loanem-backend/protos/pb/services/inventory/v1;inventoryv1b\x06proto3"

var (
	file_proto_services_inventory_v1_toolkit_proto_rawDescOnce sync.Once
	file_proto_services_inventory_v1_toolkit_proto_rawDescData []byte
)

func file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP() []byte {
	file_proto_services_inventory_v1_toolkit_proto_rawDescOnce.Do(func() {
		file_proto_services_inventory_v1_toolkit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_toolkit_proto_rawDesc), len(file_proto_services_inventory_v1_toolkit_proto_rawDesc)))
	})
	return file_proto_services_inventory_v1_toolkit_proto_rawDescData
}

var file_proto_services_inventory_v1_toolkit_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_services_inventory_v1_toolkit_proto_goTypes = []any{
	(*AddToolkitRequest)(nil),            // 0: services.inventory.v1.AddToolkitRequest
	(*AddToolkitResponse)(nil),           // 1: services.inventory.v1.AddToolkitResponse
	(*Toolkit)(nil),                      // 2: services.inventory.v1.Toolkit
	(*GetAllToolkitsRequest)(nil),        // 3: services.inventory.v1.GetAllToolkitsRequest
	(*GetAllToolkitsResponse)(nil),       // 4: services.inventory.v1.GetAllToolkitsResponse
	(*SetToolkitCourseIDRequest)(nil),    // 5: services.inventory.v1.SetToolkitCourseIDRequest
	(*SetToolkitCourseIDResponse)(nil),   // 6: services.inventory.v1.SetToolkitCourseIDResponse
	(*AddToolkitInstrumentRequest)(nil),  // 7: services.inventory.v1.AddToolkitInstrumentRequest
	(*AddToolkitInstrumentResponse)(nil), // 8: services.inventory.v1.AddToolkitInstrumentResponse
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_proto_services_inventory_v1_toolkit_proto_depIdxs = []int32{
	9, // 0: services.inventory.v1.Toolkit.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: services.inventory.v1.Toolkit.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: services.inventory.v1.GetAllToolkitsResponse.toolkits:type_name -> services.inventory.v1.Toolkit
	0, // 3: services.inventory.v1.ToolkitService.AddToolkit:input_type -> services.inventory.v1.AddToolkitRequest
	3, // 4: services.inventory.v1.ToolkitService.GetAllToolkits:input_type -> services.inventory.v1.GetAllToolkitsRequest
	7, // 5: services.inventory.v1.ToolkitService.AddToolkitInstrument:input_type -> services.inventory.v1.AddToolkitInstrumentRequest
	5, // 6: services.inventory.v1.ToolkitService.SetToolkitCourseID:input_type -> services.inventory.v1.SetToolkitCourseIDRequest
	1, // 7: services.inventory.v1.ToolkitService.AddToolkit:output_type -> services.inventory.v1.AddToolkitResponse
	4, // 8: services.inventory.v1.ToolkitService.GetAllToolkits:output_type -> services.inventory.v1.GetAllToolkitsResponse
	8, // 9: services.inventory.v1.ToolkitService.AddToolkitInstrument:output_type -> services.inventory.v1.AddToolkitInstrumentResponse
	6, // 10: services.inventory.v1.ToolkitService.SetToolkitCourseID:output_type -> services.inventory.v1.SetToolkitCourseIDResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_services_inventory_v1_toolkit_proto_init() }
func file_proto_services_inventory_v1_toolkit_proto_init() {
	if File_proto_services_inventory_v1_toolkit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_toolkit_proto_rawDesc), len(file_proto_services_inventory_v1_toolkit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_inventory_v1_toolkit_proto_goTypes,
		DependencyIndexes: file_proto_services_inventory_v1_toolkit_proto_depIdxs,
		MessageInfos:      file_proto_services_inventory_v1_toolkit_proto_msgTypes,
	}.Build()
	File_proto_services_inventory_v1_toolkit_proto = out.File
	file_proto_services_inventory_v1_toolkit_proto_goTypes = nil
	file_proto_services_inventory_v1_toolkit_proto_depIdxs = nil
}
