// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: proto/services/inventory/v1/toolkit.proto

package inventoryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ToolkitService_AddToolkit_FullMethodName         = "/services.inventory.v1.ToolkitService/AddToolkit"
	ToolkitService_SetToolkitCourseID_FullMethodName = "/services.inventory.v1.ToolkitService/SetToolkitCourseID"
)

// ToolkitServiceClient is the client API for ToolkitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ToolkitServiceClient interface {
	AddToolkit(ctx context.Context, in *AddToolkitRequest, opts ...grpc.CallOption) (*AddToolkitResponse, error)
	SetToolkitCourseID(ctx context.Context, in *SetToolkitCourseIDRequest, opts ...grpc.CallOption) (*SetToolkitCourseIDResponse, error)
}

type toolkitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewToolkitServiceClient(cc grpc.ClientConnInterface) ToolkitServiceClient {
	return &toolkitServiceClient{cc}
}

func (c *toolkitServiceClient) AddToolkit(ctx context.Context, in *AddToolkitRequest, opts ...grpc.CallOption) (*AddToolkitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddToolkitResponse)
	err := c.cc.Invoke(ctx, ToolkitService_AddToolkit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *toolkitServiceClient) SetToolkitCourseID(ctx context.Context, in *SetToolkitCourseIDRequest, opts ...grpc.CallOption) (*SetToolkitCourseIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetToolkitCourseIDResponse)
	err := c.cc.Invoke(ctx, ToolkitService_SetToolkitCourseID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToolkitServiceServer is the server API for ToolkitService service.
// All implementations must embed UnimplementedToolkitServiceServer
// for forward compatibility.
type ToolkitServiceServer interface {
	AddToolkit(context.Context, *AddToolkitRequest) (*AddToolkitResponse, error)
	SetToolkitCourseID(context.Context, *SetToolkitCourseIDRequest) (*SetToolkitCourseIDResponse, error)
	mustEmbedUnimplementedToolkitServiceServer()
}

// UnimplementedToolkitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedToolkitServiceServer struct{}

func (UnimplementedToolkitServiceServer) AddToolkit(context.Context, *AddToolkitRequest) (*AddToolkitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToolkit not implemented")
}
func (UnimplementedToolkitServiceServer) SetToolkitCourseID(context.Context, *SetToolkitCourseIDRequest) (*SetToolkitCourseIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetToolkitCourseID not implemented")
}
func (UnimplementedToolkitServiceServer) mustEmbedUnimplementedToolkitServiceServer() {}
func (UnimplementedToolkitServiceServer) testEmbeddedByValue()                        {}

// UnsafeToolkitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ToolkitServiceServer will
// result in compilation errors.
type UnsafeToolkitServiceServer interface {
	mustEmbedUnimplementedToolkitServiceServer()
}

func RegisterToolkitServiceServer(s grpc.ServiceRegistrar, srv ToolkitServiceServer) {
	// If the following call panics, it indicates UnimplementedToolkitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ToolkitService_ServiceDesc, srv)
}

func _ToolkitService_AddToolkit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToolkitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolkitServiceServer).AddToolkit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolkitService_AddToolkit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolkitServiceServer).AddToolkit(ctx, req.(*AddToolkitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ToolkitService_SetToolkitCourseID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetToolkitCourseIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToolkitServiceServer).SetToolkitCourseID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ToolkitService_SetToolkitCourseID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToolkitServiceServer).SetToolkitCourseID(ctx, req.(*SetToolkitCourseIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ToolkitService_ServiceDesc is the grpc.ServiceDesc for ToolkitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ToolkitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.inventory.v1.ToolkitService",
	HandlerType: (*ToolkitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToolkit",
			Handler:    _ToolkitService_AddToolkit_Handler,
		},
		{
			MethodName: "SetToolkitCourseID",
			Handler:    _ToolkitService_SetToolkitCourseID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/services/inventory/v1/toolkit.proto",
}
