// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/services/inventory/v1/toolkit.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToolkitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KitName       string                 `protobuf:"bytes,1,opt,name=kit_name,json=kitName,proto3" json:"kit_name,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToolkitRequest) Reset() {
	*x = AddToolkitRequest{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToolkitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToolkitRequest) ProtoMessage() {}

func (x *AddToolkitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToolkitRequest.ProtoReflect.Descriptor instead.
func (*AddToolkitRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{0}
}

func (x *AddToolkitRequest) GetKitName() string {
	if x != nil {
		return x.KitName
	}
	return ""
}

func (x *AddToolkitRequest) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type AddToolkitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToolkitResponse) Reset() {
	*x = AddToolkitResponse{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToolkitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToolkitResponse) ProtoMessage() {}

func (x *AddToolkitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToolkitResponse.ProtoReflect.Descriptor instead.
func (*AddToolkitResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{1}
}

func (x *AddToolkitResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetToolkitCourseIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolkitId     int32                  `protobuf:"varint,1,opt,name=toolkit_id,json=toolkitId,proto3" json:"toolkit_id,omitempty"`
	CourseId      int32                  `protobuf:"varint,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToolkitCourseIDRequest) Reset() {
	*x = SetToolkitCourseIDRequest{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToolkitCourseIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToolkitCourseIDRequest) ProtoMessage() {}

func (x *SetToolkitCourseIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToolkitCourseIDRequest.ProtoReflect.Descriptor instead.
func (*SetToolkitCourseIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{2}
}

func (x *SetToolkitCourseIDRequest) GetToolkitId() int32 {
	if x != nil {
		return x.ToolkitId
	}
	return 0
}

func (x *SetToolkitCourseIDRequest) GetCourseId() int32 {
	if x != nil {
		return x.CourseId
	}
	return 0
}

type SetToolkitCourseIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToolkitCourseIDResponse) Reset() {
	*x = SetToolkitCourseIDResponse{}
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToolkitCourseIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToolkitCourseIDResponse) ProtoMessage() {}

func (x *SetToolkitCourseIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_inventory_v1_toolkit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToolkitCourseIDResponse.ProtoReflect.Descriptor instead.
func (*SetToolkitCourseIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP(), []int{3}
}

var File_proto_services_inventory_v1_toolkit_proto protoreflect.FileDescriptor

const file_proto_services_inventory_v1_toolkit_proto_rawDesc = "" +
	"\n" +
	")proto/services/inventory/v1/toolkit.proto\x12\x15services.inventory.v1\"O\n" +
	"\x11AddToolkitRequest\x12\x19\n" +
	"\bkit_name\x18\x01 \x01(\tR\akitName\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"$\n" +
	"\x12AddToolkitResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"W\n" +
	"\x19SetToolkitCourseIDRequest\x12\x1d\n" +
	"\n" +
	"toolkit_id\x18\x01 \x01(\x05R\ttoolkitId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\x05R\bcourseId\"\x1c\n" +
	"\x1aSetToolkitCourseIDResponse2\xee\x01\n" +
	"\x0eToolkitService\x12a\n" +
	"\n" +
	"AddToolkit\x12(.services.inventory.v1.AddToolkitRequest\x1a).services.inventory.v1.AddToolkitResponse\x12y\n" +
	"\x12SetToolkitCourseID\x120.services.inventory.v1.SetToolkitCourseIDRequest\x1a1.services.inventory.v1.SetToolkitCourseIDResponseBGZEgithub.com/loanem-backend/protos/pb/services/inventory/v1;inventoryv1b\x06proto3"

var (
	file_proto_services_inventory_v1_toolkit_proto_rawDescOnce sync.Once
	file_proto_services_inventory_v1_toolkit_proto_rawDescData []byte
)

func file_proto_services_inventory_v1_toolkit_proto_rawDescGZIP() []byte {
	file_proto_services_inventory_v1_toolkit_proto_rawDescOnce.Do(func() {
		file_proto_services_inventory_v1_toolkit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_toolkit_proto_rawDesc), len(file_proto_services_inventory_v1_toolkit_proto_rawDesc)))
	})
	return file_proto_services_inventory_v1_toolkit_proto_rawDescData
}

var file_proto_services_inventory_v1_toolkit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_services_inventory_v1_toolkit_proto_goTypes = []any{
	(*AddToolkitRequest)(nil),          // 0: services.inventory.v1.AddToolkitRequest
	(*AddToolkitResponse)(nil),         // 1: services.inventory.v1.AddToolkitResponse
	(*SetToolkitCourseIDRequest)(nil),  // 2: services.inventory.v1.SetToolkitCourseIDRequest
	(*SetToolkitCourseIDResponse)(nil), // 3: services.inventory.v1.SetToolkitCourseIDResponse
}
var file_proto_services_inventory_v1_toolkit_proto_depIdxs = []int32{
	0, // 0: services.inventory.v1.ToolkitService.AddToolkit:input_type -> services.inventory.v1.AddToolkitRequest
	2, // 1: services.inventory.v1.ToolkitService.SetToolkitCourseID:input_type -> services.inventory.v1.SetToolkitCourseIDRequest
	1, // 2: services.inventory.v1.ToolkitService.AddToolkit:output_type -> services.inventory.v1.AddToolkitResponse
	3, // 3: services.inventory.v1.ToolkitService.SetToolkitCourseID:output_type -> services.inventory.v1.SetToolkitCourseIDResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_services_inventory_v1_toolkit_proto_init() }
func file_proto_services_inventory_v1_toolkit_proto_init() {
	if File_proto_services_inventory_v1_toolkit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_services_inventory_v1_toolkit_proto_rawDesc), len(file_proto_services_inventory_v1_toolkit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_inventory_v1_toolkit_proto_goTypes,
		DependencyIndexes: file_proto_services_inventory_v1_toolkit_proto_depIdxs,
		MessageInfos:      file_proto_services_inventory_v1_toolkit_proto_msgTypes,
	}.Build()
	File_proto_services_inventory_v1_toolkit_proto = out.File
	file_proto_services_inventory_v1_toolkit_proto_goTypes = nil
	file_proto_services_inventory_v1_toolkit_proto_depIdxs = nil
}
