syntax = "proto3";

package services.participant.v1;

import "google/protobuf/timestamp.proto";
import "proto/services/course/v1/course.proto";

option go_package = "github.com/loanem-backend/protos/pb/proto/services/participant/v1;participantv1";

service TeamService {
    rpc AddClasses(AddClassesRequest) returns (AddClassesResponse);
    rpc GetClassesByCourseID(GetClassesByCourseIDRequest) returns (GetClassesByCourseIDResponse);

    rpc AddTeams(AddTeamsRequest) returns (AddTeamsResponse);
    rpc GetTeamsByClassID(GetTeamsByClassIDRequest) returns (GetTeamsByClassIDResponse);
}

message AddClassesRequest {
    int32 course_id = 1;
    repeated string names = 2;
}

message AddClassesResponse {}

message Class {
    int32 id = 1;
    string name = 2;
    services.course.v1.Course course = 3;
    google.protobuf.Timestamp created_at = 4;
    google.protobuf.Timestamp updated_at = 5;
}

message GetClassesByCourseIDRequest {
    int32 course_id = 1;
}

message GetClassesByCourseIDResponse {
    repeated Class classes = 1;
}

message AddTeamsRequest {
    int32 class_id = 1;
    int32 number_of_teams = 2;
}

message AddTeamsResponse {}

message Team {
    string id = 1;
    Class class = 2;
    int32 number = 3;
    google.protobuf.Timestamp created_at = 4;
    google.protobuf.Timestamp updated_at = 5;
}

message GetTeamsByClassIDRequest {
    int32 class_id = 1;
}

message GetTeamsByClassIDResponse {
    repeated Team teams = 1;
}
